backend/models/Akun.php
<?php

namespace backend\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\web\IdentityInterface;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "t_akun".
 *
 * @property integer $id_akun
 * @property string $email
 * @property string $password
 * @property string $created_at
 * @property integer $id_role
 *
 * @property Role $role
 * @property Pelamar[] $pelamar
 * @property Unit[] $unit
 */
class Akun extends \yii\db\ActiveRecord implements IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_akun';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'password', 'id_role'], 'required'],
            [['created_at'], 'safe'],
            [['id_role'], 'integer'],
            [['email', 'password'], 'string', 'max' => 255],
            [['email'], 'unique'],
            [['id_role'], 'exist', 'skipOnError' => true, 'targetClass' => Role::className(), 'targetAttribute' => ['id_role' => 'id_role']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_akun' => 'Id Akun',
            'email' => 'Email',
            'password' => 'Password',
            'created_at' => 'Created At',
            'id_role' => 'Id Role',
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id_akun' => $id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by email
     *
     * @param string $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = Yii::$app->security->generatePasswordHash($password);
    }

    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRole()
    {
        return $this->hasOne(Role::className(), ['id_role' => 'id_role']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelamar()
    {
        return $this->hasMany(Pelamar::className(), ['id_akun' => 'id_akun']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnit()
    {
        return $this->hasMany(Unit::className(), ['id_akun' => 'id_akun']);
    }

    public function getIsAdmin()
    {
        return ArrayHelper::isIn($this->role->nama_role, Role::getUserAdminRoleList());
    }

    public function getIsAdminKoordinatorUnit()
    {
        return $this->role->id_role == Role::getUserRoleId('Admin Koordinator Unit');
    }

    public function getIsAdminHRD()
    {
        return $this->role->id_role == Role::getUserRoleId('Admin HRD');
    }

    public function getIsSuperAdmin()
    {
        return $this->role->id_role == Role::getUserRoleId('Super Admin');
    }

    public function getIsPelamar()
    {
        return $this->role->id_role == Role::getUserRoleId('Pelamar');
    }
    public function getNamaUnit()
    {
        return $this->Unit->nama_unit;
    }
}

backend/controllers/AkunController.php
<?php

namespace backend\controllers;

use backend\models\form\AdminHrdAddForm;
use backend\models\form\AdminKoordinatorAddForm;
//use backend\models\UnitAkunRelation;
use backend\models\Unit;
use Yii;
use backend\models\Akun;
use backend\models\Role;
//use backend\models\AkunRoleRelation;
use backend\models\AkunSearch;
use yii\web\Controller;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\IntegrityException;

/**
 * AkunController implements the CRUD actions for Akun model.
 */
class AkunController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->isSuperAdmin;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Akun models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AkunSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Akun model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionAdminHrdAdd()
    {
        $model = new AdminHrdAddForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // Start transaction
            $transaction = Yii::$app->db->beginTransaction();

            try {
                $user = new Akun();
                $user->email = $model->email;
                $user->setPassword($model->password);
                $user->id_role = Role::getUserRoleId('Admin HRD');

                if(!$user->save()) {
                    // Rollback if user not saved
                    throw new Exception('Failed to save User');
                }

            } catch (Exception $ex) {
                // Rollback if any save() failed
                $transaction->rollBack();
                die($ex->getMessage());

                return $this->render('AdminHrdAdd', [
                    'model' => $user,
                ]);
            }

            // Commit Transaction
            $transaction->commit();

            return $this->redirect(['index']);
        } else {
            return $this->render('AdminHrdAdd', [
                'model' => $model,
            ]);
        }
    }

    public function actionAdminKoordinatorAdd()
    {
        $model = new AdminKoordinatorAddForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            // Start transaction
            $transaction = Yii::$app->db->beginTransaction();

            try {
                $user = new Akun();
                $user->email = $model->email;
                $user->setPassword($model->password);
                $user->id_role = Role::getUserRoleId('Admin Koordinator Unit');

                if(!$user->save()) {
                    // Rollback if user not saved
                    throw new Exception('Failed to save User');
                }

                $unit = new Unit();
                $unit->nama_unit = $model->unit;
                $unit->id_akun = $user->id_akun;

                if(!($unit->save())) {
                    // Rollback if details not saved
                    throw new Exception('Failed to save User Details');
                }

            } catch (Exception $ex) {
                // Rollback if any save() failed
                $transaction->rollBack();
                die($ex->getMessage());

                return $this->render('AdminKoordinatorAdd', [
                    'model' => $model,
                ]);
            }

            // Commit Transaction
            $transaction->commit();

            return $this->redirect(['index']);
        } else {
            return $this->render('AdminKoordinatorAdd', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Akun model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_akun]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Akun model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        
        return $this->redirect(['index']);
    }

    /**
     * Finds the Akun model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Akun the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Akun::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/akun/AdminHRDAdd.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model backend\models\Akun */

$this->title = 'Tambah Admin HRD';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">

    <div class="col-md-6">
        <h2><?= Html::encode($this->title) ?></h2>
        <div class="panel box box-primary">
            <div class="box-header with-border">

            <?php $form = ActiveForm::begin(); ?>

                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput()?>

            <div class="form-group">
                <?= Html::submitButton('Tambah', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>

</div>

backend/views/akun/AdminKoordinatorAdd.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model backend\models\AdminKoordinatorAddForm */

$unit = ['D3 Teknik Informatika'=>'D3 Teknik Informatika','D4 Teknik Informatika'=>'D4 Teknik Informatika',
    'D3 Teknik Komputer'=>'D3 Teknik Komputer','S1 Teknik Informatika'=>'S1 Teknik Informatika',
    'S1 Sistem Informasi'=>'S1 Sistem Informasi','S1 Teknik Elektro'=>'S1 Teknik Elektro',
    'S1 Manajemen Rekayasa'=>'S1 Manajemen Rekayasa','S1 Teknik Bioproses'=>'S1 Teknik Bioproses',
    'UPT Bahasa'=>'UPT Bahasa','UPT Science and Mathematics'=>'UPT Science and Mathematics',];

$this->title = 'Tambah Admin Koordinator Unit';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">

    <div class="col-md-6">
        <h2><?= Html::encode($this->title) ?></h2>
        <div class="panel box box-primary">
            <div class="box-header with-border">

        <?php $form = ActiveForm::begin(); ?>

                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput()?>

                <?= $form->field($model, 'unit')->dropDownList($unit, ['prompt' => 'Mohon pilih Unit'])->label('Unit') ?>

        <div class="form-group">
            <?= Html::submitButton('Tambah', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

</div>

backend/views/akun/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Akun */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="akun-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'id_role')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/akun/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\AkunSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="akun-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_akun') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'id_role') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/akun/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Akun */

$this->title = 'Create Akun';
$this->params['breadcrumbs'][] = ['label' => 'Akuns', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="akun-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/akun/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\AkunSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="akun-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <p>
        <?= Html::a('Tambah Admin HRD', ['admin-hrd-add'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Tambah Koordinator Unit', ['admin-koordinator-add'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'email:email',
            [
                'label' => 'Role',
                'value' => 'role.nama_role',
                'filter' => Html::activeDropDownList($searchModel, 'user_role', \backend\models\Role::getUserRoleList(),['class'=>'form-control','prompt' => 'All']),
            ],
            
            [
                'label' => 'Action',
                'format' => 'raw',
                'value' => function($model, $key, $index, $column) {
                    return Html::a('Lihat', ['view', 'id' => $model->id_akun], ['class' => 'btn btn-primary']);
                }
            ],
        ],
    ]); ?>
</div>

backend/views/akun/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Akun */

$this->title = 'Update Akun: ' . $model->id_akun;
$this->params['breadcrumbs'][] = ['label' => 'Akuns', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_akun, 'url' => ['view', 'id' => $model->id_akun]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="akun-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/akun/view-copy.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Akun */

$this->title = $model->email;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">
    <h2>Data Akun</h2>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'email:email',
            'akunRoleRelation.userRole.nama_role',
            'created_at',
        ],
    ]) ?>

    <?= !$model->isAdmin ? '<h3>Data Pribadi</h3>' : ''?>

    <?php
    if($model->isPelamar) {
        echo DetailView::widget([
            'model' => $model,
            'attributes' => [
                'dim.nim',
                'dim.nama',
                [
                    'attribute' => 'dim.jenisKelamin.name',
                    'label' => 'Jenis Kelamin'
                ],
                [
                    'attribute' => 'dim.ttl',
                    'label' => 'Tempat Tanggal Lahir'
                ],
                'dim.prodi.name',
                [
                    'attribute' => 'dim.thn_masuk',
                    'label' => 'Angkatan'
                ],
            ],
        ]);
    } elseif($model->isAlumni) {
        echo DetailView::widget([
            'model' => $model,
            'attributes' => [
                'alumni.name',
                [
                    'attribute' => 'alumni.jenisKelamin.name',
                    'label' => 'Jenis Kelamin'
                ],
                [
                    'attribute' => 'alumni.ttl',
                    'label' => 'Tempat Tanggal Lahir'
                ],
                'alumni.prodi.name',
                'alumni.angkatan',
                'alumni.tahun_lulus',
            ],
        ]);
    }
    ?>

</div>

backend/views/akun/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Akun */
$this->title = $model->role->nama_role;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid">
    <h2>Data Akun</h2>
    <?=   Html::a('Hapus', ['delete', 'id' => $model->id_akun],[
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Apakah Anda Yakin?',
                'method' => 'post',
            ],
        ])?>

        <br>
        <br>
        

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'email:email',
            'value' => 'role.nama_role',
//            'value' => 'unit.nama_unit',
            // 'unit.nama_unit',
            'created_at',
        ],
    ]) ?>

</div>